services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
